version: '2'

volumes:
  nextcloud:
  db:

services: 
  db: 
    image: postgres:latest
    restart: always
    volumes: 
      - db:/var/lib/mysql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=nextcloud
  app:
    image: nextcloud
    ports: 
      - 5004:80
    links: 
      - db 
    volumes:
      - /media/nextcloudStore:/var/www/html
    restart: always